<?php
namespace ApiOauth2Server\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OAuthAccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthAccessTokenRepository extends EntityRepository
{
    public function getAccessTokenById($accessToken)
    {
        $qb = $this->createQueryBuilder('at')
            ->where('at.accessToken = :accessToken')
            ->setParameter('accessToken', $accessToken);

        return $qb->getQuery()->useResultCache(true, 3600, $accessToken);
    }

    public function getUnexpiredAccessTokenByClientIdUserId($clientId, $userId)
    {
        $qb = $this->createQueryBuilder('at')
            ->where('at.clientId = :clientId')
            ->andWhere('at.userId = :userId')
            ->andWhere('at.expires > :expires')
            ->setParameters(array(
                'clientId' => $clientId,
                'userId'   => $userId,
                'expires'  => date_create(),
            ));

        return $qb->getQuery();
    }
}
