<?php

namespace ApiOauth2Server\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OAuthUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthUserRepository extends EntityRepository
{
    public function getUserByUsernameAndPassword($username, $password)
    {
        $queryBuilder = $this->createQueryBuilder('u')
            ->where('u.userName = :username')
            ->andWhere('u.password = :password')
            ->setParameters(array(
                'username' => $username,
                'password' => $password,
            ));

        return $queryBuilder->getQuery();
    }

    public function getUserWithScopeAndClientByUsernameAndClientId($username, $clientId)
    {
        $qb = $this->createQueryBuilder('u')
            ->addSelect(array('u.userId'))//'s.scope' don support for now
            ->leftJoin('u.scopes', 's')
            ->where('u.userName = :username')
            ->andWhere('s.clientId = :clientId')
            ->setParameters(array(
                'username' => $username,
                'clientId' => $clientId,
            ));

        return $qb->getQuery();
    }
}
