<?php
namespace ApiOauth2Server\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OAuthAccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthAccessTokenRepository extends EntityRepository
{
    public function getUnexpiredAccessTokenByClientIdUserId($clientId, $userId)
    {
        $queryBuilder = $this->createQueryBuilder('at')
            ->where('at.clientId = :clientId')
            ->andWhere('at.userId = :userId')
            ->andWhere('at.expires > :expires')
            ->setParameters(array(
                'clientId' => $clientId,
                'userId'   => $userId,
                'expires'  => date_create(),
            ));

        return $queryBuilder->getQuery();
    }
}
