<?php
namespace ApiOauth2Server\Model\Repository;

use ApiOauth2Server\Model\Entity\OAuthRefreshToken as RToken;

use Doctrine\ORM\EntityRepository;

/**
 * OAuthRefreshTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthRefreshTokenRepository extends EntityRepository
{
    public function getRefreshTokenById($refreshToken)
    {
        $qb = $this->createQueryBuilder('rt')
            ->where('rt.refreshToken = :refreshToken')
            ->setParameter('refreshToken', $refreshToken);

        return $qb->getQuery()->useResultCache(true, 3600, $refreshToken);
    }

    public function getUnusedRefreshTokenByClientIdAndUserIdAndScope($clientId, $userId, $scope)
    {
        $qb = $this->createQueryBuilder('rt')
            ->where('rt.clientId = :clientId')
            ->andWhere('rt.userId = :userId')
            ->andWhere('rt.scope = :scope')
            ->andWhere('rt.used = :used AND rt.expires > :expires')
            ->setParameters(array(
                'clientId' => $clientId,
                'userId'   => $userId,
                'scope'    => $scope,
                'used'     => RToken::USED_NO,
                'expires'  => date_create(),
            ));

        return $qb->getQuery();
    }
}
